### ISSUE TITLE
Repetition

### ISSUE THREAD

**Issue by ghost** [System303/prj-rev-bwfs-dasmoto#7]
https://github.com/System303/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L10-L16

You've written a lot of code here that gets needlessly repeated. You should move shared styles into their own CSS rule with multiple selectors, or with a more general selector.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Notice I didn't include the font-family, since that's a style that should be getting applied to the whole page. Use the universal selector `*` to reduce repetition even further.

```css
* {
  font-family: Helvetica;
}
```
